entityTypes = {
	attack:[
		{time:120},
		{time:60},
		{time:300},
		{time:240},
		{time:180},
		{time:150},
		{time:90},
		{time:48},
		{time:180},
		{time:150},
		{time:120},//10
		{time:105},
		{time:75},
		{time:45},
		{time:210},
		{time:120},
		{time:10},
		{time:150},
		{time:165},
		{time:120},
		{time:90},//20
		{time:60},
		{time:48},
		{time:300},
		{time:180},
		{time:120},
		{time:90},
		{time:150},
		{time:105},
		{time:45},
		{time:75},//30
		{time:60},
		{time:48},
		{time:240},
		{time:150},
		{time:45},
		{time:180},
		{time:120},
		{time:105},
		{time:90},
		{time:90},//40
		{time:60},
		{time:120},
		{time:180},
		{time:180},
		{time:180},
		{time:120},
		{time:120},
		{time:60},
		{time:72},
		{time:72},//50
		{time:48},
	],
	projectile:[
		{
			name:"Blaster Laser",
			size:5,
			speed:8,
			time:120,
		},{
			name:"Machine Laser",
			size:3,
			speed:6,
			time:120,
		},{
			name:"Infantry Rocket",
			size:5,
			speed:5,
			time:240,
		},{
			name:"Sniper Laser",
			size:5,
			speed:16,
			time:180,
		},{
			name:"Heavy Laser",
			size:8,
			speed:7,
			time:120,
		},{
			name:"Shot Laser",
			size:2.5,
			speed:8,
			time:90,
		},{
			name:"Secondary Shot Laser",
			size:2.5,
			speed:10,
			time:90,
		},{
			name:"Aggressor Laser",
			size:6,
			speed:7,
			time:120,
		},{
			name:"Heavy Sniper Laser",
			size:6,
			speed:16,
			time:180,
		},{
			name:"Shot Laser",
			size:3,
			speed:8,
			time:90,
		},{
			name:"Flashbang",
			size:5,
			speed:10,
			time:240,
		},{
			name:"Burst",
			size:6,
			speed:10.5,
			time:180,
		},{
			name:"Burst2",
			size:5,
			speed:12,
			time:180,
		},
	],
	enemy:[
		{
			name:"Assault Robot",
			life:10,block:0,
			width:20,height:64,
			damage:5,speed:1.5, 
			push:0.5,parry:0,physics:0,
			attack:{range:400,speed:1,stop:false,class:0},
		},{
			name:"Scout Robot",
			life:10,block:20,
			width:20,height:64,
			damage:15,speed:2,
			push:0.5,parry:2,physics:0,
			attack:{range:50,speed:0.8,stop:true,class:1},
		},{
			name:"Heavy Robot",
			life:20,block:0,
			width:20,height:64,
			damage:3,speed:1,
			push:0.25,parry:0,physics:0,
			attack:{range:500,speed:1,stop:false,class:2},
		},{
			name:"Rocket Robot",
			life:15,block:0,
			width:20,height:64,
			damage:25,speed:1.25,
			push:0.25,parry:0,physics:0,
			attack:{range:550,speed:1,stop:false,class:3},
		},{
			name:"Sniper Robot",
			life:10,block:0,
			width:20,height:64,
			damage:15,speed:0.75,
			push:0.5,parry:0,physics:0,
			attack:{range:900,speed:1,stop:false,class:4},
		},{
			name:"Shot Robot",
			life:10,block:0,
			width:20,height:64,
			damage:4,speed:1.75,
			push:0.5,parry:0,physics:0,
			attack:{range:350,speed:1,stop:false,class:5},
		},{
			name:"Assault Robot Commander",
			life:20,block:0,
			width:20,height:64,
			damage:5,speed:1.65,
			push:0.5,parry:0,physics:0,
			attack:{range:450,speed:1,stop:false,class:6},
		},{
			name:"Scout Robot Commander",
			life:20,block:40,
			width:20,height:64,
			damage:15,speed:2.2,
			push:0.5,parry:2,physics:0,
			attack:{range:50,speed:0.8,stop:true,class:7},
		},{
			name:"Heavy Robot Commander",
			life:40,block:0,
			width:20,height:64,
			damage:3,speed:1.1,
			push:0.25,parry:0,physics:0,
			attack:{range:500,speed:1,stop:false,class:8},
		},{
			name:"Rocket Robot Commander",
			life:30,block:0,
			width:20,height:64,
			damage:25,speed:1.75,
			push:0.25,parry:0,physics:0,
			attack:{range:650,speed:1,stop:false,class:9},
		},{
			name:"Sniper Robot Commander",
			life:20,block:0,
			width:20,height:64,
			damage:15,speed:0.825,
			push:0.5,parry:0,physics:0,
			attack:{range:1200,speed:1,stop:false,class:10},
		},{
			name:"Shot Robot Commander",
			life:20,block:0,
			width:20,height:64,
			damage:4,speed:1.925,
			push:0.5,parry:0,physics:0,
			attack:{range:425,speed:1,stop:false,class:11},
		},{
			name:"Management Officer",
			life:25,block:0,
			width:30,height:90,
			damage:5,speed:1.75,
			push:1,parry:0,physics:0,
			attack:{range:450,speed:1,stop:false,class:12},
		},{
			name:"Management Trooper",
			life:50,block:0,
			width:30,height:90,
			damage:5,speed:2,
			push:1,parry:0,physics:0,
			attack:{range:600,speed:1,stop:false,class:13},
		},{
			name:"Management Shadow Trooper",
			life:80,block:0,
			width:30,height:90,
			damage:20,speed:2.5,
			push:1,parry:0,physics:0,
			attack:{range:300,speed:1,stop:false,class:14},
		},{
			name:"Management Walker Driver",
			life:35,block:0,
			width:30,height:90,
			damage:20,speed:1.5,
			push:1,parry:0,physics:0,
			attack:{range:500,speed:1,stop:false,class:6},
		},{
			name:"Turret",
			life:10,block:0,
			width:20,height:20,
			damage:5,speed:0,
			push:1,parry:0,physics:1,
			attack:{range:600,speed:1,stop:true,class:15},
		},{
			name:"Target",
			life:10,block:0,
			width:20,height:20,
			damage:0,speed:0,
			push:1,parry:0,physics:1,
			attack:{range:0,speed:1,stop:true,class:0},
		},{
			name:"Ramming Robot",
			life:10,block:10,
			width:20,height:64,
			damage:5,speed:2.25, 
			push:0.5,parry:10,physics:0,
			attack:{range:15,speed:0.8,stop:true,class:16},
		},{
			name:"Ramming Robot Commander",
			life:20,block:20,
			width:20,height:64,
			damage:5,speed:2.475, 
			push:0.5,parry:10,physics:0,
			attack:{range:15,speed:0.8,stop:true,class:16},
		},{
			name:"Sweeper Robot",
			life:15,block:0,
			width:36,height:30,
			damage:5,speed:4,
			push:1,parry:0,physics:1,
			attack:{range:600,speed:1,stop:true,class:15},
		},{
			name:"Management Heavy Trooper",
			life:100,block:0,
			width:30,height:90,
			damage:3,speed:1.35,
			push:0.5,parry:0,physics:0,
			attack:{range:750,speed:1,stop:false,class:17},
		},{
			name:"Management Rocket Trooper",
			life:75,block:0,
			width:30,height:90,
			damage:25,speed:1.65,
			push:0.5,parry:0,physics:0,
			attack:{range:825,speed:1,stop:false,class:18},
		},{
			name:"Volley Robot",
			life:10,block:0,
			width:20,height:64,
			damage:5,speed:1.5, 
			push:0.5,parry:0,physics:0,
			attack:{range:400,speed:1,stop:false,class:19},
		},{
			name:"Volley Robot Commander",
			life:20,block:0,
			width:20,height:64,
			damage:5,speed:1.65,
			push:0.5,parry:0,physics:0,
			attack:{range:450,speed:1,stop:false,class:20},
		},{
			name:"Shock Robot",
			life:10,block:20,
			width:20,height:64,
			damage:15,speed:2,
			push:0.5,parry:2,physics:0,
			attack:{range:50,speed:0.8,stop:true,class:21},
		},{
			name:"Shock Robot Commander",
			life:20,block:40,
			width:20,height:64,
			damage:15,speed:2.2,
			push:0.5,parry:2,physics:0,
			attack:{range:50,speed:0.8,stop:true,class:22},
		},{
			name:"Overlock Robot",
			life:20,block:0,
			width:20,height:64,
			damage:3,speed:1,
			push:0.25,parry:0,physics:0,
			attack:{range:500,speed:1,stop:false,class:23},
		},{
			name:"Overlock Robot Commander",
			life:40,block:0,
			width:20,height:64,
			damage:3,speed:1.1,
			push:0.25,parry:0,physics:0,
			attack:{range:500,speed:1,stop:false,class:24},
		},{
			name:"Aggressor Robot",
			life:10,block:0,
			width:20,height:64,
			damage:8,speed:1.5, 
			push:0.5,parry:0,physics:0,
			attack:{range:400,speed:1,stop:false,class:25},
		},{
			name:"Aggressor Robot Commander",
			life:20,block:0,
			width:20,height:64,
			damage:8,speed:1.65,
			push:0.5,parry:0,physics:0,
			attack:{range:450,speed:1,stop:false,class:26},
		},{
			name:"Dualcloud Robot",
			life:10,block:0,
			width:20,height:64,
			damage:4,speed:1.75,
			push:0.5,parry:0,physics:0,
			attack:{range:350,speed:1,stop:false,class:27},
		},{
			name:"Dualcloud Robot Commander",
			life:20,block:0,
			width:20,height:64,
			damage:4,speed:1.925,
			push:0.5,parry:0,physics:0,
			attack:{range:425,speed:1,stop:false,class:28},
		},{
			name:"Management Aggressor Trooper",
			life:50,block:0,
			width:30,height:90,
			damage:8,speed:2,
			push:1,parry:0,physics:0,
			attack:{range:600,speed:1,stop:false,class:29},
		},{
			name:"Management Shot Trooper",
			life:50,block:0,
			width:30,height:90,
			damage:4,speed:2.35,
			push:1,parry:0,physics:0,
			attack:{range:525,speed:1,stop:false,class:30},
		},{
			name:"Parry Robot",
			life:10,block:20,
			width:20,height:64,
			damage:15,speed:2,
			push:0.5,parry:2,physics:0,
			attack:{range:50,speed:0.8,stop:true,class:31},
		},{
			name:"Parry Robot Commander",
			life:20,block:40,
			width:20,height:64,
			damage:15,speed:2.2,
			push:0.5,parry:2,physics:0,
			attack:{range:50,speed:0.8,stop:true,class:32},
		},{
			name:"Barrage Robot",
			life:15,block:0,
			width:20,height:64,
			damage:25,speed:1.25,
			push:0.25,parry:0,physics:0,
			attack:{range:550,speed:1,stop:false,class:33},
		},{
			name:"Barrage Robot Commander",
			life:30,block:0,
			width:20,height:64,
			damage:25,speed:1.75,
			push:0.25,parry:0,physics:0,
			attack:{range:650,speed:1,stop:false,class:34},
		},{
			name:"Scout Purge Robot",
			life:40,block:80,
			width:20,height:64,
			damage:20,speed:3,
			push:0.5,parry:3,physics:0,
			attack:{range:50,speed:0.8,stop:true,class:7},
		},{
			name:"Assault Purge Robot",
			life:40,block:0,
			width:20,height:64,
			damage:8,speed:2.25, 
			push:0.5,parry:0,physics:0,
			attack:{range:550,speed:1,stop:false,class:35},
		},{
			name:"Management Archivist",
			life:20,block:0,
			width:30,height:90,
			damage:5,speed:1.75,
			push:1,parry:0,physics:0,
			attack:{range:450,speed:1,stop:false,class:12},
		},{
			name:"Heavy Turret",
			life:20,block:0,
			width:20,height:20,
			damage:5,speed:0,
			push:1,parry:0,physics:1,
			attack:{range:750,speed:1,stop:true,class:15},
		},{
			name:"Heavy Purge Robot",
			life:80,block:0,
			width:20,height:64,
			damage:5,speed:1.5,
			push:0.25,parry:0,physics:0,
			attack:{range:700,speed:1,stop:false,class:36},
		},{
			name:"Sniper Purge Robot",
			life:40,block:0,
			width:20,height:64,
			damage:20,speed:1.125,
			push:0.5,parry:0,physics:0,
			attack:{range:1250,speed:1,stop:false,class:37},
		},{
			name:"Shot Purge Robot",
			life:40,block:0,
			width:20,height:64,
			damage:6,speed:1.75,
			push:0.5,parry:0,physics:0,
			attack:{range:475,speed:1,stop:false,class:38},
		},{
			name:"Panicked Management Officer",
			life:25,block:0,
			width:30,height:90,
			damage:0,speed:4,
			push:2,parry:0,physics:0,
			attack:{range:0,speed:0,stop:false,class:0},
		},{
			name:"Advanced Robot",
			life:120,block:0,
			width:20,height:64,
			damage:5,speed:1.25, 
			push:0.5,parry:0,physics:0,
			attack:{range:400,speed:1,stop:false,class:0},
		},{
			name:"Storm Commando",
			life:200,block:0,
			width:30,height:90,
			damage:5,speed:2.25, 
			push:0.5,parry:0,physics:0,
			attack:{range:500,speed:1,stop:false,class:0},
		},{
			name:"Agent Belisar",
			life:180,block:0,
			width:30,height:90,
			damage:5,speed:3, 
			push:0.5,parry:0,physics:0,
			attack:{range:1200,speed:1,stop:false,class:0},
		},{
			name:"Heavy Purge",
			life:240,block:60,
			width:25,height:80,
			damage:30,speed:0.8, 
			push:0.125,parry:4,physics:0,
			attack:{range:70,speed:0.8,stop:false,class:42},
		},{
			name:"Rocket Troop",
			life:160,block:0,
			width:30,height:90,
			damage:5,speed:2.5, 
			push:0.5,parry:0,physics:0,
			attack:{range:600,speed:1,stop:false,class:0},
		},{
			name:"Management Walker",
			life:600,block:0,
			width:60,height:240,
			damage:5,speed:0.5, 
			push:0,parry:0,physics:0,
			attack:{range:1200,speed:1,stop:false,class:0},
		},{
			name:"Daschorb",
			life:300,block:0,
			width:45,height:90,
			damage:5,speed:1, 
			push:0.25,parry:0,physics:0,
			attack:{range:450,speed:1,stop:false,class:0},
		},{
			name:"Exterminator",
			life:400,block:100,
			width:20,height:64,
			damage:5,speed:2.5,
			push:0.125,parry:1,physics:0,
			attack:{range:50,speed:1,stop:true,class:0},
		},{
			name:"Grand Admiral Acosi",
			life:999,block:999,
			width:30,height:90,
			damage:60,speed:2,
			push:0,parry:1,physics:0,
			attack:{range:600,speed:1,stop:true,class:51},
		},
	],
};
dialogues = [
	{
		back:[0,0,0,1],
		stack:["Good to see you made it back!\nI was beginning to miss you!","Oh, it was nothing, sis. I've only been out a\ncouple days, it shouldn't be such a big deal.","I'm going to go train now. See you around.","I'm going to get some things\nset up to practice against."],
		name:["Lira","Setsuna","Setsuna","Setsuna"],
	},{
		back:[2,3],
		stack:["I have to go now. I should be back by\nthe afternoon, it's nothing much.","Don't do anything I wouldn't do."],
		name:["Setsuna","Setsuna"],
	},{
		back:[4,5],
		stack:["I need to get back home,\nit's getting late.","What's going on down there?","I haven't seen those before,\nwhat are they doing?","They don't look friendly,\nI should be careful."],
		name:["Setsuna","Setsuna","Setsuna","Setsuna"],
	},{
		back:[6,6,6,7,7],
		stack:["Looks like they're all gone.\nThat was much more dangerous than I thought.","The rest of them must have moved toward the town.\nI better catch up before they do anything.","Why would they go here?\nDo they have a reason for this?","I wasn't looking to fight them, they just started\nattacking! I couldn't have done anything!","I'll focus on their movements for now.\nIf any more appear, I might have to fight them."],
		name:["Setsuna","Setsuna","Setsuna","Setsuna","Setsuna"],
	},{
		back:[8,8,8,9,9,9],
		stack:["Lira, I was worried about you, it's good to see\nyou're okay. Did something happen around here?","Uh, well, they attacked, but I\nstayed away from them, there were too many.","But mom, she... didn't make it. I'm sorry, Setsuna.\nShe's gone, and I failed to protect her.","It's fine. You couldn't have done anything with how many of\nthem there were. Did you see which direction they left in?","No, Setsuna! It's not worth risking attacking\nthem for revenge. Their strength is overwhelming!","I'm going to do it, Lira.\nAre you on my side or not?"],
		name:["Setsuna","Lira","Lira","Setsuna","Lira","Setsuna"],
	},{
		back:[10,10,10,10],
		stack:["Command? This is SC-18-040 reporting.","The nearby robot patrols have been significantly\nreduced by our target. We do not have a location.","I'll keep an eye for now, but reinforcements\nmight be necessary. Relay this to Belisar.","Make no mistake, commander.\nWe are under attack."],
		name:["???","???","???","???"],
	},{
		back:[11,11,12],
		stack:["Now that he's dealt with, what do I do know?\nI have to find the ones responsible for this...","There should be something on him that will\nlead me to the people that ordered this.","I guess I'll start with these documents\ndetailing his division's movements..."],
		name:["Setsuna","Setsuna","Setsuna"],
	},{
		back:[13,13,14,14],
		stack:["Here it is. Looks like a base for their miliary.\nThis place could be somewhat dangerous,\nI should check for a security system.","Some of them just entered recently, and security\nlooks to have been lowered. I should be able to find an\nentrance somewhere, but the front is a little too risky.","Looks like they didn't notice me, but there's more\nguards up ahead. I'll have to fight my way through.","I don't know the layout of this place, but I can at\nleast tell which way the command center is in."],
		name:["Setsuna","Setsuna","Setsuna","Setsuna"],
	},{
		back:[15,15,15,15],
		stack:["So, here you are.","If you think you're getting somewhere with what you're\ndoing, you're not. This is much larger than you think.","I'm not aware of a possible greater situation,\nbut I know what you did to us.","You have no idea."],
		name:["Agent Belisar","Agent Belisar","Setsuna","Agent Belisar"],
	},{
		back:[16,16,17],
		stack:["I've won here, but I don't believe\nhe was the one who called the attack.","There's got to be more information\naround this base. I know it.","These documents, they discuss who ordered the attack.\nLooks to be a high-ranking officer, named Acosi."],
		name:["Setsuna","Setsuna","Setsuna"],
	},{
		back:[18,18,18,18,18,18],
		stack:["I'm sorry, but Acosi may be an unreachable\ntarget. I wouldn't go after him.","He's the Oversector 424 Grand Admiral.\nHe controls all the Management forces around here.\nYou can't touch him.","Why not? A well-planned strike through his\nguard may be enough to take him for good.","Acosi prides himself in being untouchable. We\nhaven't had a confirmed location for years. He could\nbe on the other side of galaxy and we wouldn't know.","Would it be possible to draw him\nin by threataning his operations?","Maybe, but it'll be hard. Security around here\ncan be extremely heavy, and we have no guarantees.","It's fine.\nI just want a shot at the man who destroyed my life."],
		name:["Umbito","Umbito","Setsuna","Umbito","Setsuna","Umbito","Setsuna"],
	},{
		back:[19,19,20],
		stack:["Soldiers! I ordered you to find the target.\nIt should not be taking this long,\nwith your numbers compared to theirs.","Somehow they've destroyed a huge portion of\nyour forces, without you even detecting them!","If you don't get this perpetrator I'll have you all-"],
		name:["???","???","???"],
	},{
		back:[21,21,21,21,21],
		stack:["That's the construction on Alicu disabled.\nAnd there will be more to come for the Management.","Keep doing things like this, and we'll cause\nquite a lot of trouble. I've been tracking\nAcosi in the meantime, but there's little information.","The only thing we know, is that he isn't around\nhere. We have no concrete proof,\nbut I would place him in Oversector 465.","I can keep disrupting his operations.\nEventually he'll have to do something about it.","You have a personal way of\ngetting things done. I like it."],
		name:["Setsuna","Umbito","Umbito","Setsuna","Umbito"],
	},{
		back:[18,18,18],
		stack:["Looks like what we did last time has affected\nthe Management, but it's not enough.\nAcosi won't be acting on it.","We'll need to continually cause\ndamage if we want him to notice.","So where to next?"],
		name:["Umbito","Umbito","Setsuna"],
	},{
		back:[22,22,23,24],
		stack:["Okay, looks like that was\nall of them in this area.","I should move on to the next enemy divisions\nbefore they leave for the base.","With effective planning, I will be able to\ncut off their escape and defeat them.","Better getting moving,\ncan't let them get out of here."],
		name:["Setsuna","Setsuna","Setsuna","Setsuna"],
	},{
		back:[25,25,25,25],
		stack:["Another successful attack. A couple more, and Acosi\nwill be pressured into returning to stop us.","My Management Officer informants have told\nme that there's chaos in the ranks.","Good. It's only a matter of time\nbefore our plans can go into action.","Let's return and find our next target. There\nare plenty of Management operations around here."],
		name:["Setsuna","Umbito","Setsuna","Umbito"],
	},{
		back:[18,18,18],
		stack:["We have found our next target,\nand it may well be our greatest. A full Management\nconvoy, headed for the airfield on Collass.","This'll be the one, Setsuna. This will be\ngreater than anything they could've imagined.","I'm happy to hear that. Get to\npreparing, this'll be a difficult one."],
		name:["Umbito","Umbito","Setsuna"],
	},{
		back:[26,26,27],
		stack:["There it is...\nthe end of the convoy.","It's amazing that they haven't\nnoticed their allies are dead.","Let's finish this."],
		name:["Setsuna","Setsuna","Setsuna"],
	},{
		back:[28,28,28,28,28],
		stack:["This was a big one.\nThose reinforcements were headed for the\nColloss salient. Without those reinforcements, the\nManagement may give have to up the airfield.","Acosi won't let that happen. He'll be back\nwith a replacement army in no time.\nExactly what we want.","That was some of my best work. Their\nforces were strongly disorganized,\nand I broke through their flanks.","But I think the Management is learning\nfrom me. They're deploying new units\ndesigned to slow my advance.","The Management isn't filled with idiots.\nWe both know that. There's plenty\nof competent officers within their ranks."],
		name:["Umbito","Umbito","Setsuna","Setsuna","Umbito"],
	},{
		back:[18,18,18,18,18,18,29,29],
		stack:["We have Acosi right where we want him.\nReports mention his entry into the sector.\nIt's time to strike, Setsuna.","So where can we strike without\nencountering major Management forces?","That's the issue. We don't know where he is.\nBut I know how and where we can find out.","As he has entered the sector, his\ninformation should have entered the archives.\nIf you break in, we should be able to obtain it.","You will have to break your way up to the\ntop floor, where the most important records\nare stored. We cannot enter from the\ntop due to the defensive perimeter.","With skillful piloting, we should be able\nto access the lower entry point, but\nit'll be hard to avoid all the fighters.","The sector Management Archive.\nIt's a grand building, isn't it? Shame so\nmuch work was wasted on something like this.","I'll hold off the defense forces below this\npoint and disable the communications.\nYou go on ahead."],
		name:["Umbito","Setsuna","Umbito","Umbito","Umbito","Umbito","Umbito","Umbito"],
	},{
		back:[30,39],
		stack:["The files should be just ahead.","Of course the most important ones\nare stored in the safest places."],
		name:["Setsuna","Setsuna"],
	},{
		back:[31,31,32,32,32,32,32,32,32,32,8,8,8],
		stack:["Here, I got what I went for. They really\nwere on the top floor. Acosi must be\nimportant for them to keep security so high.","All the files describe the most\nrecent information about their target, so\nthis should contain all the information we need.","Location data describes his path\nthrough the Rouxon Nebula.\nThat will make his ship, Prudence, tracable.","Wait, what's this tab?\nI didn't know these files contained familial data.\nDoes Acosi have a family?","Two daughters, named...no...","I didn't know...","It all makes sense now...\nWhy I never saw my father.\nThey said he was out at work...","Well, I can't change the truth.\nThis is who I am now...","So what do we do?","Plan the attack as before.\nI'll go get tell my sister...","Lira, I've discovered the truth about our father.\nThis may be too much for you, but...","What is it, sis?","I'll tell you, but first,\nwe need to get out of here."],
		name:["Setsuna","Setsuna","Umbito","Umbito","Setsuna","Umbito","Setsuna","Setsuna","Umbito","Setsuna","Setsuna","Lira","Setsuna"],
	},{
		back:[33,33,33,33],
		stack:["Let's go over the plan one last time. The Prudence\npasses through the Rouxon Nebula tomorrow.\nWe will use the nebula's electromagnetic\nsignature to remain undetected.","I will infiltrate the ship's lower\ncontrol center to cause a distraction.\nYou too will launch a direct assault on the bridge.","I'm going to take the lead. If we use\nthe outside edge, we won't have\nto fight through too many defense forces.","You just guard my back, okay?"],
		name:["Umbito","Umbito","Setsuna","Setsuna"],
	},{
		back:[34,34,34,34,34],
		stack:["This is it. The bridge.","There's no going back now, Lira.","What is he going to do with us?","I don't know. We'll find out.\nFollow my lead to keep yourself safe.","I don't know...\nHe could be dangerous."],
		name:["Setsuna","Setsuna","Lira","Setsuna","Lira"],
	},{
		back:[35,35,36,36,36,36,37,38,38,38,38,38,38,38],
		stack:["Acosi...please. Don't hurt her.","Lira's only a child, she didn't know\nwhat she was getting into...\nI dragged her into it.","Lira?\nTell me, how did you two get here?","We're sisters...from Konai.\nMost of the damage we caused you was her doing.","Wait...I see now. I know what has occured.\nIt is a terrible misfortune that this had to happen.","Get up.\nI'm sure I can explain everything.","That won't be necessary.","Ha, Belisar, that idiot.\nHe was responsible for this whole mess.\nGood thing he's gone.","His decision to kill to cover up his own\nmistakes will not be forgiven, but death cuts\neverything short, it seems.","I've taken full responsibility for\ndealing with the perpetrators.\nThey're in better places now.","Acosi remains on our side for the time\nbeing. I'll consider promoting him, to make\nup for everything he's gone through.","Always the retributionist, I see.\nThings are inherently unfair, you should remember.\nYou don't need to make up for other's mistakes.","Whatever happens, just let us all\nforget about the incident.\nReturn the world to normalcy.","I've decided to reorganize the Management\nAutomated Military. Too much incompetency\nand too many weaknesses. They must be\neliminated for a maximum efficiency machine."],
		name:["Setsuna","Setsuna","Grand Admiral Acosi","Lira","Grand Admiral Acosi","Grand Admiral Acosi","???","The Manager","The Manager","The Manager","Executive Chairman","The Manager","The Manager","The Manager"],
	},
];
stage = {scene:"cut",level:8,zone:0,focus:{x:0,y:0},edge:{x:0,y:0},check:{x:0,y:0},time:0,blind:0,key:0,lock:0};
inputs = {keys:[false,false,false,false,false],specialKeys:[false,false,false,false],mouse:{x:0,y:0}};
entities = {projectiles:[],particles:[],enemies:[],players:[],walls:[]};
physics = {gravity:0.5,friction:0.95,resistance:0.975};
runOrder = {back:[],fore:[entities.projectiles,entities.enemies,entities.players,entities.particles,entities.walls],life:[entities.enemies,entities.players]};
collision = {incident:{x:0,y:0},calculate:{x:0,y:0}};
transition = {anim:0,trigger:false,scene:stage.scene,level:stage.level,zone:stage.zone,spawn:1,return:false,respawn:false,remember:[]};
graphics = {full:0,backgrounds:[],cut:[],entities:{clouds:[[],[],[],[]]}};
dialogue = {id:0,back:[],stack:[],name:[],fade:0,maintain:0,trigger:false};
hold = {constant:[0,0,0,0],win:false,cutlist:[2,4,7,10,13,16,19,22],anim:[0,0,0,0,0,0,0,0],name:["Konai\nOutskirts","Konai\nCentral Range","Konai\nMountain Fortress","Alicu\nConstruction Zone","Farcosa\nMineral Extraction Facility","Collass\nPrimary Airfield","Ofsuz\nManagement Archives","Rouxon Nebula\nPrudence"]};
levelDetail = [];
a = 0;b = 0;c = 0;d = 0;e = 0;f = 0;g = 0;h = 0;i = 0;j = 0;
